# Generated by Django 3.2.11 on 2022-02-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doneapp', '0005_rename_country_booking_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='district',
        ),
    ]
